#this is for link

scr=main.c init_op.c basic_shapes.c print_board.c mouse_op.c chess_op.c
para=-o main -Wall
main:$(scr)
		gcc $(scr) $(para)

#main:m.c aa.c
#		gcc m.c aa.c -o main -Wall
clean:
		rm -rf *.o
		rm -rf main 
		rm -rf ~*
run:
		./main
